#page title
page_title                                : UpRead                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1454094961                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /assets/presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : UpRead - Speed Reading                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Read faster. No training required.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : CrazyHorseApps
your_link                                 : https://crazyhorseapps.com                     
your_city                                 :                                 
email_address                             : help.chapps@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Read faster. Read more
    description                           : UpRead is designed to help you read faster from the get-go and to be less stressful on your vision when using mobile devices.
    fontawesome_icon_name                 : bolt
    
  - title                                 : No training required
    description                           : No need for boring exercises or prior training. You can use UpRead without any experience and still gain most of the benefits.
    fontawesome_icon_name                 : dumbbell

  - title                                 : In your pocket
    description                           : UpRed works great, especially on iPhone, allowing you to read comfortably and quickly even on a small screen.
    fontawesome_icon_name                 : mobile

  - title                                 : Backed by science
    description                           : We developed UpRead based on promising scientific evidence and experiments. It helps all readers, including those with ADHD or vision impairments.
    fontawesome_icon_name                 : flask

  - title                                 : Progress with time
    description                           : Even if UpRead does not require training, experience will make you faster and more comfortable with the reading method.
    fontawesome_icon_name                 : star
  
  - title                                 : Books, artickes, docs
    description                           : UpRead supports a wide range of data sources, including web pages, PDF files, and TXT files.
    fontawesome_icon_name                 : book

  - title                                 : Customizable
    description                           : You can configure the speed, reading technique, look, colors, and more within the app.
    fontawesome_icon_name                 : cog



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                                           # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#2A2A2A"

link_color                                : "#DD4C4F"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#aaaaaa"

feature_icons_foreground_color            : "#2A2A2A"
feature_icons_background_color            : "#ffffff"

social_icons_foreground_color             : "#2A2A2A"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#aaaaaa"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
